# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: suchait-consulting-pool

steps:
  
- task: Docker@2
  inputs:
    containerRegistry: 'retailsolution01'
    repository: 'urbanretail/confluentconnect'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: '1.0'

